
# Global options
baseURL = "/"
canonifyURLs = true
copyright = "© 2023 by Sakib Reza. <a href='/privacy'>Privacy policy</a>."
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]
languageCode = "en"
theme = "barks"
title = "Sakib Reza"



# Main menu
[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 2
[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 2
[[menu.main]]
    name = "Publications"
    url  = "/publications"
    weight = 2
#[[menu.main]]
#    name = "Teaching"
#    url  = "/teaching"
#    weight = 2



# Customization options
[params]

    [params.head]
        author = "Sakib Reza"
        custom_css = "/custom.css"
        description = "Hi, I'm Sakib"
        keywords = ["cryptography", "academic", "ETH", "security", "doctorate"]

    [params.navigation]
        show_navigation = true

    [params.footer]
        show_footer = true

    [params.typography]
#        title_font = "Urbanist"
        title_font = "Cutive Mono"
        body_font = "Source Sans Pro"

    [params.colors]
        theme_color = "#333333"
        background_color = "#fcfbf9"
        text_color = "#333333"
        link_color = "#17442a"

    [params.social]
        [params.social.email]
            name = "E-Mail"
            class = "fas fa-envelope"
            url = "mailto:reza.s@northeastern.edu"
            weight = 1
        [params.social.linkedin]
            name = "LinkedIn"
            class = "fab fa-linkedin"
            url = "https://www.linkedin.com/in/sakibreza"
            weight = 2
        [params.social.linkedin]
            name = "Twitter"
            class = "fab fa-twitter"
            url = "https://twitter.com/sakib_reza"
            weight = 3
        [params.social.github]
            name = "GitHub"
            class = "fab fa-github"
            url = "https://github.com/sakibreza"
            weight = 4
        [params.social.google_scholar]
            name = "Google Scholar"
            class = "ai ai-google-scholar-square"
            url = "https://scholar.google.com/citations?user=gBAA-V8AAAAJ&hl=en"
            weight = 5
        [params.social.institution]
            name = "My institution"
            class = "fas fa-university"
            url = "https://www.sail-nu.com/sakib-reza"
            weight = 6
        


# Options for Markdown renderer
[markup]

    [markup.goldmark.renderer]
        unsafe = true
        xHTML = true

    [markup.highlight]
        style = 'dracula'
