/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 21
#define YY_END_OF_BUFFER 22
static yyconst short int yy_accept[256] =
    {   0,
       14,   14,   22,   20,   21,   15,   18,   17,   16,   20,
       20,   20,   10,   14,   19,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,    9,   12,    8,    0,   10,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
        1,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    6,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,

       14,   14,   14,   14,    0,    0,    0,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,    4,
       14,   14,    2,    5,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,    7,   14,   14,   14,    1,
        3,   14,   14,   14,   14,   14,    4,   14,    1,   14,
       14,   14,   14,    0,    5,   14,    0,   10,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,    7,    7,
       14,   14,    7,   14,   14,   14,    5,   14,   14,   14,

       14,   14,    0,    0,   11,   14,   12,   14,   14,   14,
       14,    7,   14,   14,    7,    7,   14,   14,   14,   14,
       14,    4,    0,   13,   14,   14,   14,   14,   14,    7,
       14,   14,    7,   14,   14,    0,    0,   14,   14,    7,
       14,    7,    0,    0,   14,   14,    7,    7,    0,    4,
        7,    0,    7,    0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    5,    6,    1,    1,
        1,    7,    1,    1,    1,    8,    9,   10,   11,   12,
       13,   10,   10,   10,   10,   10,   10,    1,    1,    1,
        1,    1,    1,    1,   14,   14,   14,   14,   15,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   16,   14,   14,   14,   14,   14,   14,   14,
        1,    1,    1,   17,   18,    1,   19,   20,   21,   22,

       23,   24,   25,   26,   27,   14,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       42,   43,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[44] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    1,    3,
        3,    3,    3,    3,    3,    3,    1,    1,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3
    } ;

static yyconst short int yy_base[270] =
    {   0,
        0,    0,  190, 1301, 1301, 1301, 1301, 1301, 1301,  180,
       34,   41,   41,   45, 1301,   49,   53,   79,   49,   93,
       68,   67,   89,  109,  110,  114,  125,   72,  151,  165,
      155,  118,  153,  154, 1301,  104, 1301,  183,  196,  202,
      208,  198,  203,  210,  215,  217,  234,  227,  238,  242,
      246,  255,  259,  270,  255,  283,  284,  289,  295,  299,
      305,  306,  311,  321,  325,  329,  334,  341,  372,  381,
      390,  382,  387,  388,  406,  413,  407,  427,  429,  435,
      434,  450,  457,  455,  461,  470,  481,  476,  496,  496,
      497,  508,  520,  503,  525,  534,  539,  543,  548,  555,

      560,  561,  566,  582,   54,   58,   88,  584,  589,  590,
      608,  338,  609,  610,  615,  616,  617,  632,  636,  188,
      643,  643,  652,  660,  668,  672,  677,  684,  689,  690,
      696,  708,  715,  720,  727,  733,  739,  739,  755,  754,
      760,  761, 1301,  794,  798,  802,  806,  798,  804,  805,
      691,  810,  818,  819,  832,  425,  831,  842,  849,  880,
      857,  869,  833,  871,  876,  883,  884,  888,  896,  905,
      902,  911,  912,  155,  945,  949,  953,  959,  950,  945,
      949,  966,  965,  980,  985,  989,  993,  993, 1025, 1029,
     1020, 1021, 1039, 1025, 1033, 1042, 1049, 1000, 1049, 1051,

     1065, 1066,  149, 1092, 1098, 1088, 1111, 1089, 1099, 1108,
     1112, 1131, 1119, 1123, 1143, 1154, 1134, 1135, 1146, 1158,
     1147, 1162,  163, 1187, 1173, 1177, 1163, 1182, 1194,    0,
     1200, 1201, 1232, 1212, 1243,  139,  155, 1217, 1228,    0,
     1241, 1253,  134,  124, 1245, 1245, 1277, 1281,  138, 1301,
     1285,  140,    0,  119, 1301, 1297,  147,  142,  128,  123,
      118,  107,  106,  104,   92,   76,   74,   68,   64
    } ;

static yyconst short int yy_def[270] =
    {   0,
      255,    1,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  256,  257,  255,  257,  257,  257,   18,   18,
       18,   18,   20,   18,   18,   18,   18,  257,  257,  257,
      257,   20,   18,   18,  255,  255,  255,  255,  256,  256,
      256,   18,   18,   30,   30,   18,   18,   20,   20,   20,
       20,   20,   20,   20,   30,   18,   18,   20,   18,   30,
       30,   30,   30,   20,   20,   20,   30,   30,  256,  256,
      256,   30,   30,   30,   30,   18,   30,   30,   30,   30,
       30,   30,   18,   30,   30,   30,   30,   30,   18,   30,
       30,   30,   18,   30,   18,   18,   18,   18,   18,   30,

       30,   30,   30,   30,  255,  255,  255,   30,   30,   30,
       30,   20,   30,   30,   30,   30,   30,   18,   30,  258,
       30,   18,   18,   18,   18,   18,   18,   30,   30,   30,
       30,   30,   18,   18,   30,   30,   18,   30,   30,   30,
       30,   30,  255,  257,  257,  257,  257,   30,   18,   30,
       20,   20,   20,   20,   20,  259,   30,   30,   30,  260,
       30,   18,   20,   20,   30,   30,   30,   20,   20,   30,
       20,   30,   30,  255,  257,  257,  255,  256,   30,   20,
       18,   18,   18,   18,   18,   18,   30,   20,  261,  259,
       30,   30,  262,   20,   20,   30,   30,   18,   18,   18,

       18,   18,  255,  255,  256,   18,  255,   30,   18,   18,
       30,  261,   18,   30,  263,  262,   30,   30,   30,   18,
       20,   20,  255,  255,   20,   20,   18,   30,   30,  264,
       30,   30,  263,   30,  265,  255,  255,   20,   20,  266,
       18,  267,  255,  255,   30,   20,  268,  267,  255,  255,
      268,  255,  269,  255,    0,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255
    } ;

static yyconst short int yy_nxt[1345] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       13,   13,   13,   14,   14,   14,   15,    4,   16,   17,
       18,   19,   20,   21,   22,   14,   23,   14,   24,   25,
       26,   27,   28,   14,   29,   30,   31,   32,   33,   34,
       14,   14,   14,   36,   36,   36,   36,   35,   38,   37,
       39,   39,   39,   39,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,  253,   42,  143,  143,
      251,   49,  143,  143,   42,   50,  248,   42,  240,   43,
       51,   41,   69,   70,   71,   42,   42,   44,   41,   41,
       41,   41,   42,   42,  242,   59,   56,   45,   60,   57,

       72,   61,  143,  143,   46,   58,  230,   47,  233,  216,
       48,   42,   51,   36,   36,   36,   36,   42,   42,   62,
      212,   52,   42,   53,   42,  193,   54,   42,   42,   42,
      190,   63,   42,   55,   42,   42,   65,   42,   42,   42,
       64,   42,   42,   42,  156,   67,   42,   66,   79,   42,
       42,   42,  250,   42,  254,  252,   42,  250,   42,   68,
       41,   41,   41,   41,   41,   41,   41,   41,  249,  244,
      243,   80,   42,   73,   41,   41,   41,   41,   42,   82,
      237,   42,   42,  223,   81,   42,  203,   74,   35,  255,
      255,   75,   36,   36,   36,   36,   78,   41,   41,   41,

       41,   76,  255,   38,   77,   39,   39,   39,   39,  255,
      255,  255,  255,  255,  255,  255,   42,   41,   41,   41,
       41,   42,  255,   42,   68,  255,   42,  255,   42,   42,
      255,   42,   83,  255,   42,   85,   42,   42,  255,  255,
      255,   42,   42,  255,  255,   42,   42,  255,   42,   42,
       84,   42,   86,  255,   42,   42,   87,   88,  255,   42,
       42,   89,   42,  255,  255,   42,   42,   42,   42,  255,
       42,   42,   42,  255,   42,   42,   42,   42,   42,   42,
       90,   42,   42,   42,  255,   42,   42,   42,   42,   42,
       91,   94,   42,  255,   42,   42,   92,  255,   42,   42,

       42,   42,   42,   42,  255,  255,  255,   93,   42,   42,
       42,   42,   42,   42,   95,   42,  255,   42,   51,   96,
       42,   42,   42,   42,  255,   42,   97,   99,   42,   42,
      255,   42,   42,   42,  255,   98,  255,   42,   42,  255,
      255,   42,  100,  255,   42,   42,  101,   42,  255,   42,
       42,  102,  255,   42,   42,  103,   42,  104,   42,   42,
       42,   42,   42,   42,  255,   42,   42,   42,  148,   42,
       68,   42,  255,   42,  255,  255,  255,   42,   42,  255,
       42,   41,   41,   41,   41,  255,  255,  255,  255,  105,
       41,   41,   41,   41,  255,  255,  255,  255,  106,   41,

       41,   41,   41,  255,   42,  255,  255,  107,   42,   42,
       42,  109,  255,   42,   42,  255,  255,  111,   42,  108,
      255,   42,  255,  110,   42,  255,   42,   42,   42,   42,
      112,  114,   42,  116,  189,  189,  189,  189,   42,  255,
      255,   42,   42,   42,   42,   42,   42,  115,  113,   42,
      255,   42,  255,   42,  255,  118,   42,   42,  255,  117,
      121,   42,  122,   42,  119,   42,   42,  255,   42,  120,
       42,   42,   42,   42,   42,  124,  123,   51,  255,  255,
      255,   42,   42,   42,  255,   42,   42,   42,   42,   42,
      255,   42,   42,  255,   42,  125,   42,   42,   42,  255,

       42,  255,   42,   42,  255,  126,   42,   42,  255,   42,
      127,  128,  129,  255,  130,   42,  255,   42,   42,   51,
       42,   42,  131,   42,   42,  134,  255,   42,  255,   42,
       42,  255,   42,   42,   42,   42,   42,  132,  133,   42,
      255,  255,   42,  135,   42,   42,  255,   42,   42,  255,
       42,   42,   42,   42,  136,  255,   42,   42,  137,   42,
      255,   42,   42,  255,   42,   42,  138,   42,   42,  255,
       42,   42,  255,   42,   51,  255,   42,  139,  255,   42,
      255,   42,   42,   42,  255,   51,   42,   42,   42,  255,
      255,   42,   42,  255,   42,  140,   42,   42,  255,   42,

       42,  255,   42,  141,   42,   42,   42,  255,   42,  255,
       42,   42,   42,  255,  255,  145,   42,  255,  142,  144,
       42,   42,  255,   42,  255,   42,   42,  146,   42,   42,
       42,  149,   42,  255,  147,   42,   42,   42,   42,  153,
      255,  151,   42,   42,   42,   42,  150,   42,   42,   42,
       42,   42,  152,   42,   42,   42,   42,   42,   42,  255,
       42,  157,  155,  154,   51,   42,  255,  255,   42,   42,
       42,   42,   42,  255,   42,   42,  255,   42,   42,   42,
      158,  255,   42,   42,  255,   42,  159,   51,   42,  255,
       42,   42,  255,   42,  255,  161,   42,   42,  255,   42,

       42,  255,   42,   42,  255,   42,   42,  160,   42,  255,
       42,   42,   42,  255,  255,  163,   42,  165,   42,   42,
      162,  185,   42,   42,   42,   42,   42,  164,   42,   42,
      166,   42,   42,   42,   42,   42,  255,  255,   42,  255,
       42,  255,  255,  167,   42,   42,   42,   42,   42,   42,
      255,   42,  255,   42,  168,   42,  255,  171,  255,   42,
      255,   42,  255,  169,   42,   42,   42,   42,  255,  170,
       42,  174,   42,  255,  255,  172,   42,   42,   42,  173,
       42,   42,   42,   42,  255,  255,   42,  176,  255,  255,
       42,   42,  255,   42,   42,  175,   42,   42,  255,   42,

       42,  177,  255,  178,  178,  178,  178,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,  255,
      182,  255,   42,  255,   42,  255,  181,   42,  255,   42,
      186,  184,   42,  179,   42,  183,  180,   42,   42,  187,
       42,   42,  255,   42,   42,  255,   42,   42,   42,   51,
       42,   42,   42,   42,  255,  255,  188,   42,   42,   42,
       42,   42,   42,  195,   51,   42,   42,  191,   42,  192,
       42,   42,   42,   42,  255,   42,  255,  255,   42,   42,
      255,   42,  255,   42,  255,   42,  255,  194,   42,   41,
       41,   41,   41,   42,   42,  255,   42,   42,  197,  196,

       42,   42,   42,  255,   42,   42,   42,  255,  255,   42,
       42,   42,   42,  255,  255,   42,   42,  198,  199,   42,
       42,   42,   42,   42,   42,  255,   42,   42,   42,   42,
       51,  200,   42,  201,  202,   42,   42,   42,   42,  255,
      255,   42,   42,  255,   42,  255,  255,   42,   42,  255,
       42,   42,  204,  255,  205,  205,  205,  205,   41,   41,
       41,   41,  207,  207,  207,  207,  177,   42,  178,  178,
      178,  178,   42,   42,   42,   51,   42,   42,   42,  255,
      209,  206,  255,   42,   42,   42,  208,   51,   51,   42,
       42,   42,  255,   42,   42,  255,   42,   42,   42,  255,

       51,  255,  255,   42,  255,   42,  255,   42,   42,   51,
       42,   42,  255,   42,   51,  210,   42,   42,  219,   42,
       42,   42,  255,  211,  255,   42,   42,  255,   42,   42,
      255,   42,   42,   42,  189,  189,  189,  189,  189,  189,
      189,  189,   42,   42,  255,  255,  213,   42,  215,  215,
      215,  215,  255,   42,  255,  217,   42,  214,   42,   42,
       42,   42,  255,   42,   42,   42,   42,  220,   42,   42,
      218,   42,  255,   42,   42,   42,   42,   42,   51,   42,
       42,   42,  221,   42,   42,   42,  255,  255,   42,  255,
       42,   42,  255,   42,   42,  255,   42,   42,  255,  222,

       51,  224,  224,  224,  224,  204,   42,  205,  205,  205,
      205,  226,  255,   42,  255,   42,  225,   42,  255,   42,
      207,  207,  207,  207,   42,   42,   42,  227,   42,  255,
       42,  228,  255,   42,  229,  255,   42,   42,   42,   42,
      230,  230,  230,  230,   42,  232,  255,  231,   42,   42,
       42,   42,  215,  215,  215,  215,   42,  169,  255,   42,
       42,   42,   42,  215,  215,  215,  215,  255,   42,  255,
       51,   42,   42,   42,   42,   42,   42,  235,  255,  236,
       42,   42,  234,   42,  255,   42,   51,   42,   42,   42,
       42,   42,   42,  255,  238,   42,  224,  224,  224,  224,

      255,   42,   42,   42,   42,   42,   42,   42,  239,  255,
       42,   51,  255,   42,  197,   51,   42,   42,   42,  255,
       42,   42,   51,   42,  255,  255,   42,   42,  255,  255,
       42,  255,  255,   42,   42,   51,   42,   42,  241,   42,
       42,  240,  240,  240,  240,   42,  255,  161,   42,  255,
       42,   42,   41,   41,   41,   41,   42,   42,  245,   42,
      255,   42,  247,  247,  247,  247,   42,   51,   42,   42,
      255,   42,  246,   42,  255,   51,  255,  255,   42,  255,
      255,   42,  255,  255,   42,   42,  247,  247,  247,  247,
      247,  247,  247,  247,  253,  253,  253,  253,   40,   40,

        3,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255
    } ;

static yyconst short int yy_chk[1345] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   11,   11,   11,   11,   12,   13,   12,
       13,   13,   13,   13,   14,   14,   14,   14,   16,   16,
       16,   16,   17,   17,   17,   17,  269,   19,  105,  105,
      268,   19,  106,  106,   19,   19,  267,   19,  266,   16,
       19,   28,   28,   28,   28,   22,   21,   17,   18,   18,
       18,   18,   22,   21,  265,   22,   21,   18,   22,   21,

       28,   22,  107,  107,   18,   21,  264,   18,  263,  262,
       18,   20,   23,   36,   36,   36,   36,   23,   20,   23,
      261,   20,   23,   20,   20,  260,   20,   24,   25,   23,
      259,   24,   26,   20,   24,   25,   25,   24,   25,   26,
       24,   25,   26,   27,  258,   26,   32,   25,   32,  257,
       27,   32,  254,   27,  252,  249,   27,  244,   32,   27,
       29,   29,   29,   29,   31,   31,   31,   31,  243,  237,
      236,   33,   34,   29,   30,   30,   30,   30,   33,   34,
      223,   33,   34,  203,   33,   34,  174,   30,   10,    3,
        0,   30,   38,   38,   38,   38,   31,  120,  120,  120,

      120,   30,    0,   39,   30,   39,   39,   39,   39,   40,
        0,   40,   40,   40,   40,   41,   42,   41,   41,   41,
       41,   43,    0,   42,   43,    0,   42,    0,   43,   42,
        0,   43,   44,    0,   43,   46,   44,   45,    0,    0,
        0,   45,   46,    0,    0,   46,   44,    0,   46,   44,
       45,   45,   47,    0,   45,   48,   48,   48,    0,   47,
       48,   49,   47,    0,    0,   47,   49,   48,   49,    0,
       50,   49,   50,    0,   51,   50,   51,   55,   49,   51,
       50,   55,   50,   52,    0,   52,   51,   53,   52,   53,
       52,   55,   53,    0,   55,   52,   53,    0,   54,   53,

       54,   56,   57,   54,    0,    0,    0,   54,   56,   57,
       54,   56,   57,   59,   56,   57,    0,   58,   57,   58,
       59,   60,   58,   59,    0,   60,   59,   61,   62,   58,
        0,   61,   62,   63,    0,   60,    0,   63,   60,    0,
        0,   61,   62,    0,   61,   62,   63,   63,    0,   64,
       63,   64,    0,   65,   64,   65,   67,   66,   65,   66,
       67,   64,   66,   68,    0,   65,  112,   68,  112,   66,
       67,  112,    0,   67,    0,    0,    0,   68,  112,   69,
       68,   69,   69,   69,   69,    0,    0,    0,   70,   69,
       70,   70,   70,   70,    0,    0,    0,   71,   70,   71,

       71,   71,   71,    0,   72,    0,    0,   71,   72,   73,
       74,   73,    0,   73,   74,    0,    0,   74,   72,   72,
        0,   72,    0,   73,   74,    0,   73,   74,   75,   77,
       75,   76,   75,   77,  156,  156,  156,  156,   76,    0,
        0,   76,   75,   77,   76,   75,   77,   76,   75,   78,
        0,   79,    0,   78,    0,   79,   81,   80,    0,   78,
       81,   80,   81,   78,   79,   79,   78,    0,   79,   80,
       81,   80,   82,   81,   80,   83,   82,   84,    0,    0,
        0,   84,   83,   85,    0,   83,   82,   85,   83,   82,
        0,   84,   86,    0,   84,   85,   86,   85,   88,    0,

       85,    0,   88,   87,    0,   86,   86,   87,    0,   86,
       87,   88,   88,    0,   89,   88,    0,   87,   90,   91,
       87,   89,   90,   91,   89,   94,    0,   89,    0,   94,
       92,    0,   90,   91,   92,   90,   91,   92,   93,   94,
        0,    0,   94,   95,   92,   93,    0,   92,   93,    0,
       95,   93,   96,   95,   96,    0,   95,   97,   97,   96,
        0,   98,   96,    0,   97,   96,   99,   97,   98,    0,
       97,   98,    0,   99,   98,    0,   99,  100,    0,   99,
        0,  100,  101,  102,    0,  102,  101,  102,  103,    0,
        0,  100,  103,    0,  100,  101,  101,  102,    0,  101,

      102,    0,  103,  103,  104,  103,  108,    0,  104,    0,
      108,  109,  110,    0,    0,  109,  110,    0,  104,  108,
      108,  104,    0,  108,    0,  109,  110,  110,  109,  110,
      111,  113,  114,    0,  111,  113,  114,  115,  116,  117,
        0,  115,  116,  117,  111,  113,  114,  111,  113,  114,
      118,  115,  116,  117,  115,  116,  117,  118,  119,    0,
      118,  122,  119,  118,  121,  121,    0,    0,  122,  121,
      123,  122,  119,    0,  122,  119,    0,  123,  124,  121,
      123,    0,  121,  123,    0,  124,  125,  124,  124,    0,
      126,  124,    0,  125,    0,  127,  125,  126,    0,  125,

      126,    0,  127,  126,    0,  127,  128,  126,  127,    0,
      128,  129,  130,    0,    0,  129,  130,  131,  131,  151,
      128,  151,  131,  128,  151,  129,  130,  130,  129,  130,
      132,  151,  131,  133,  132,  131,    0,    0,  134,    0,
      133,    0,    0,  133,  132,  134,  133,  132,  134,  135,
        0,  134,    0,  135,  134,  136,    0,  137,    0,  136,
        0,  138,    0,  135,  137,  138,  135,  137,    0,  136,
      137,  140,  136,    0,    0,  138,  140,  139,  138,  139,
      140,  139,  141,  142,    0,    0,  141,  142,    0,    0,
      140,  139,    0,  140,  139,  141,  141,  142,    0,  141,

      142,  144,    0,  144,  144,  144,  144,  145,  145,  145,
      145,  146,  146,  146,  146,  147,  147,  147,  147,    0,
      148,    0,  149,    0,  148,    0,  147,  150,    0,  149,
      152,  150,  149,  145,  148,  149,  146,  148,  152,  153,
      152,  150,    0,  152,  150,    0,  153,  154,  153,  154,
      152,  153,  154,  157,    0,    0,  155,  157,  153,  154,
      155,  163,  155,  163,  158,  155,  163,  157,  158,  159,
      157,  159,  155,  163,    0,  159,    0,    0,  158,  161,
        0,  158,    0,  161,    0,  159,    0,  162,  159,  160,
      160,  160,  160,  161,  162,    0,  161,  162,  165,  164,

      162,  164,  165,    0,  164,  166,  167,    0,    0,  166,
      167,  164,  165,    0,    0,  165,  168,  166,  168,  166,
      167,  168,  166,  167,  169,    0,  169,  170,  168,  169,
      171,  170,  171,  172,  173,  171,  169,  172,  173,    0,
        0,  170,  171,    0,  170,    0,    0,  172,  173,    0,
      172,  173,  175,    0,  175,  175,  175,  175,  176,  176,
      176,  176,  177,  177,  177,  177,  178,  181,  178,  178,
      178,  178,  179,  180,  181,  180,  179,  181,  180,    0,
      181,  176,    0,  183,  182,  180,  179,  182,  183,  179,
      183,  182,    0,  183,  182,    0,  183,  182,  184,    0,

      184,    0,    0,  185,    0,  184,    0,  186,  184,  185,
      185,  184,    0,  185,  186,  187,  185,  186,  198,  187,
      186,  188,    0,  188,    0,  198,  188,    0,  198,  187,
        0,  198,  187,  188,  189,  189,  189,  189,  190,  190,
      190,  190,  191,  192,    0,    0,  191,  192,  193,  193,
      193,  193,    0,  194,    0,  194,  191,  192,  194,  191,
      192,  195,    0,  195,  196,  194,  195,  199,  196,  200,
      195,  197,    0,  195,  199,  197,  200,  199,  196,  200,
      199,  196,  200,  201,  202,  197,    0,    0,  197,    0,
      201,  202,    0,  201,  202,    0,  201,  202,    0,  201,

      202,  204,  204,  204,  204,  205,  206,  205,  205,  205,
      205,  208,    0,  206,    0,  208,  206,  209,    0,  206,
      207,  207,  207,  207,  209,  208,  210,  209,  208,    0,
      209,  210,    0,  210,  211,    0,  210,  213,  211,  210,
      212,  212,  212,  212,  213,  214,    0,  213,  211,  214,
      213,  211,  215,  215,  215,  215,  217,  218,    0,  214,
      217,  218,  214,  216,  216,  216,  216,    0,  219,    0,
      217,  218,  219,  217,  218,  221,  220,  221,    0,  222,
      221,  227,  219,  220,    0,  219,  220,  221,  227,  220,
      222,  227,  222,    0,  227,  222,  224,  224,  224,  224,

        0,  225,  222,  225,  228,  226,  225,  226,  228,    0,
      226,  226,    0,  225,  225,  229,  229,  226,  228,    0,
      229,  228,  231,  232,    0,    0,  231,  232,    0,    0,
      229,    0,    0,  229,  234,  232,  231,  232,  234,  231,
      232,  233,  233,  233,  233,  238,    0,  238,  234,    0,
      238,  234,  235,  235,  235,  235,  239,  238,  239,  241,
        0,  239,  242,  242,  242,  242,  241,  245,  239,  241,
        0,  245,  241,  246,    0,  246,    0,    0,  246,    0,
        0,  245,    0,    0,  245,  246,  247,  247,  247,  247,
      248,  248,  248,  248,  251,  251,  251,  251,  256,  256,

      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "ohi.l"
#define INITIAL 0
#line 2 "ohi.l"
	#include<stdio.h>
	int keywords=0,bracket=0,punctuations=0,reloperators=0,arioperators=0,logoperators=0,identifiers=0,ipositive=0,inegative=0,fpositive=0,fnegative=0,strings=0;
#line 747 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 21 "ohi.l"

#line 900 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 256 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1301 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 22 "ohi.l"
{
				printf("keyword \"%s\" \n",yytext);
				keywords++;
			}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 26 "ohi.l"
{
				printf("bracket \"%s\" \n",yytext);
				bracket++;
			}	
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 30 "ohi.l"
{
				printf("punctuation \"%s\" \n",yytext);
				punctuations++;
			}					
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 34 "ohi.l"
{
				printf("relational_operator \"%s\" \n",yytext);
				reloperators++;
			}						
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 38 "ohi.l"
{
				printf("arithmetic_operator \"%s\" \n",yytext);
				arioperators++;
			}									
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 42 "ohi.l"
{
				printf("logical_operator \"%s\" \n",yytext);
				logoperators++;
			}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 46 "ohi.l"
{
				printf("the identifier \"%s\" \n",yytext);
				identifiers++;
			}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 50 "ohi.l"
printf("%s is a Single line Command\n ", yytext);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 51 "ohi.l"
printf("%s is a multi line command \n", yytext);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 53 "ohi.l"
{
				printf("positive integer_number \"%s\" \n",yytext);
				ipositive++;
			}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 57 "ohi.l"
{
				printf("negative integer_number \"%s\" \n",yytext);
				inegative++;
			}			
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 61 "ohi.l"
{
				printf("positive float_number \"%s\" \n",yytext);
				fpositive++;
			}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 65 "ohi.l"
{
				printf("negative float_number \"%s\" \n",yytext);
				fnegative++;
			}			
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 69 "ohi.l"
{
				printf("the string \"%s\" \n",yytext);
				strings++;
			}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 73 "ohi.l"
printf("%s is a Hash Sign\n ", yytext);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 74 "ohi.l"
printf("%s is a Ampersand \n", yytext);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 75 "ohi.l"
printf("%s is a Percentange Sign \n", yytext);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 76 "ohi.l"
printf("%s is a Dollar Sign \n", yytext);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 77 "ohi.l"
printf("%s is a Power Sign \n", yytext);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 80 "ohi.l"

	YY_BREAK
case 21:
YY_RULE_SETUP
#line 81 "ohi.l"
ECHO;
	YY_BREAK
#line 1124 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 256 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 256 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 255);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 81 "ohi.l"

int yywrap()
{
	return 1;
}
int main()
{
	yyin=freopen("input.txt","r",stdin);
	yylex();
	printf("Total keywords: %d\n",keywords);
	printf("Total brackets: %d\n",bracket);
	printf("Total punctuations: %d\n",punctuations);
	printf("Total relational operators: %d\n",reloperators);
	printf("Total arithmetic operators: %d\n",arioperators);
	printf("Total logical operators: %d\n",logoperators);
	printf("Total Operators found: %d\n",reloperators+arioperators+logoperators);
	printf("Total Integer numbers(positive and negative): %d and %d\n",ipositive,inegative);
	printf("Total Float numbers(positive and negative): %d and %d\n",fpositive,fnegative);
	printf("Total Strings: %d\n",strings);
	printf("Total identifiers found: %d\n",identifiers);
	fclose(yyin);
	return 0;
}